/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author windows
 */
public class Interfaz extends javax.swing.JFrame {

    
    main principal=new main();
    main2 princi=new main2();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NOMBREOBRA = new javax.swing.JTextField();
        NOMBRELIBRO = new javax.swing.JTextField();
        AUTORLIBRO = new javax.swing.JTextField();
        AUTOROBRA = new javax.swing.JTextField();
        AÑOLIBRO = new javax.swing.JTextField();
        AÑOOBRA = new javax.swing.JTextField();
        jButton1NOMBRELIBRO = new javax.swing.JButton();
        jButton2ANOMBREOBRA = new javax.swing.JButton();
        jButton3AUTORLIBRO = new javax.swing.JButton();
        jButton4AUTOROBRA = new javax.swing.JButton();
        jButton5AÑOLIBRO = new javax.swing.JButton();
        jButton6AÑOBRA = new javax.swing.JButton();
        jButton7MOSTRARBIBLIO = new javax.swing.JButton();
        jButton8MOSTRARMUSEO = new javax.swing.JButton();
        jButton9BIBLIOTODO = new javax.swing.JButton();
        jButton10MUSEOTODO = new javax.swing.JButton();
        jButton11LIMPIAR = new javax.swing.JButton();
        jButton12SALIR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1RESULTADO = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 255));

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        jLabel1.setText("Museos Y Bibliotecas");

        jButton1NOMBRELIBRO.setText("BUSCAR EL LIBRO ");
        jButton1NOMBRELIBRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1NOMBRELIBROActionPerformed(evt);
            }
        });

        jButton2ANOMBREOBRA.setText("BUSCAR LA OBRA ");
        jButton2ANOMBREOBRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ANOMBREOBRAActionPerformed(evt);
            }
        });

        jButton3AUTORLIBRO.setText("BUSCAR LIBROS DEL AUTOR");

        jButton4AUTOROBRA.setText("BUSCAR OBRAS DEL AUTOR");

        jButton5AÑOLIBRO.setText("BUSCAR LIBROS PUBLICADOS EL AÑO ");

        jButton6AÑOBRA.setText("BUSCAR OBRAS PUBLICADAS EL AÑO ");
        jButton6AÑOBRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6AÑOBRAActionPerformed(evt);
            }
        });

        jButton7MOSTRARBIBLIO.setText("MOSTRAR BIBLIOTECAS");
        jButton7MOSTRARBIBLIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7MOSTRARBIBLIOActionPerformed(evt);
            }
        });

        jButton8MOSTRARMUSEO.setText("MOSTRAR MUSEOS");
        jButton8MOSTRARMUSEO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8MOSTRARMUSEOActionPerformed(evt);
            }
        });

        jButton9BIBLIOTODO.setText("MOSTAR BIBLIOTECAS Y LIBROS");
        jButton9BIBLIOTODO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9BIBLIOTODOActionPerformed(evt);
            }
        });

        jButton10MUSEOTODO.setText("MOSTRAR MUSEOS Y OBRAS");
        jButton10MUSEOTODO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10MUSEOTODOActionPerformed(evt);
            }
        });

        jButton11LIMPIAR.setText("LIMPIAR");
        jButton11LIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11LIMPIARActionPerformed(evt);
            }
        });

        jButton12SALIR.setText("SALIR");
        jButton12SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12SALIRActionPerformed(evt);
            }
        });

        jTextArea1RESULTADO.setColumns(20);
        jTextArea1RESULTADO.setRows(5);
        jScrollPane1.setViewportView(jTextArea1RESULTADO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(263, 263, 263))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1NOMBRELIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2ANOMBREOBRA, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3AUTORLIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4AUTOROBRA, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5AÑOLIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6AÑOBRA, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NOMBRELIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AÑOOBRA, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AÑOLIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AUTOROBRA, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AUTORLIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NOMBREOBRA, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11LIMPIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7MOSTRARBIBLIO, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8MOSTRARMUSEO, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10MUSEOTODO, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9BIBLIOTODO, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NOMBRELIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1NOMBRELIBRO))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NOMBREOBRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2ANOMBREOBRA))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AUTORLIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3AUTORLIBRO))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AUTOROBRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4AUTOROBRA))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AÑOLIBRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5AÑOLIBRO))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AÑOOBRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6AÑOBRA))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7MOSTRARBIBLIO)
                            .addComponent(jButton9BIBLIOTODO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8MOSTRARMUSEO)
                            .addComponent(jButton10MUSEOTODO))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11LIMPIAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12SALIR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ANOMBREOBRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ANOMBREOBRAActionPerformed
        // TODO add your handling code here:
        String nombreobra= NOMBREOBRA.getText();
        princi.buscarAutorEnMuseos(PilaA a,String nombreobra);
    }//GEN-LAST:event_jButton2ANOMBREOBRAActionPerformed

    private void jButton6AÑOBRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6AÑOBRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6AÑOBRAActionPerformed

    private void jButton7MOSTRARBIBLIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7MOSTRARBIBLIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MOSTRARBIBLIOActionPerformed

    private void jButton8MOSTRARMUSEOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8MOSTRARMUSEOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MOSTRARMUSEOActionPerformed

    private void jButton9BIBLIOTODOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9BIBLIOTODOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9BIBLIOTODOActionPerformed

    private void jButton10MUSEOTODOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10MUSEOTODOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MUSEOTODOActionPerformed

    private void jButton11LIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11LIMPIARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11LIMPIARActionPerformed

    private void jButton12SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12SALIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12SALIRActionPerformed

    private void jButton1NOMBRELIBROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1NOMBRELIBROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1NOMBRELIBROActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AUTORLIBRO;
    private javax.swing.JTextField AUTOROBRA;
    private javax.swing.JTextField AÑOLIBRO;
    private javax.swing.JTextField AÑOOBRA;
    private javax.swing.JTextField NOMBRELIBRO;
    private javax.swing.JTextField NOMBREOBRA;
    private javax.swing.JButton jButton10MUSEOTODO;
    private javax.swing.JButton jButton11LIMPIAR;
    private javax.swing.JButton jButton12SALIR;
    private javax.swing.JButton jButton1NOMBRELIBRO;
    private javax.swing.JButton jButton2ANOMBREOBRA;
    private javax.swing.JButton jButton3AUTORLIBRO;
    private javax.swing.JButton jButton4AUTOROBRA;
    private javax.swing.JButton jButton5AÑOLIBRO;
    private javax.swing.JButton jButton6AÑOBRA;
    private javax.swing.JButton jButton7MOSTRARBIBLIO;
    private javax.swing.JButton jButton8MOSTRARMUSEO;
    private javax.swing.JButton jButton9BIBLIOTODO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1RESULTADO;
    // End of variables declaration//GEN-END:variables
}
